"use client";

import { useEffect, useState, useRef } from "react";
import { Rocket, Sparkles, Brain, Calculator, BookOpen, FlaskConical, Code2, Puzzle, Play, Moon, Sun, Star, Clock3, Trophy, Map, X, Volume2, Pause, RotateCcw, ChevronRight, Check, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Flag, Coffee } from "lucide-react";
import { useTheme } from "next-themes";
import { Game, type Kind } from "./play";

export const ages = ["5–7 anos", "8–10 anos", "11–12 anos", "13–15 anos"];
const games: {id:Kind; name:string; desc:string; subject:string; icon:typeof Brain; color:string}[] = [
  {id:"math",name:"Estação dos números",desc:"Uma conta, várias descobertas. Encontre a resposta!",subject:"Matemática",icon:Calculator,color:"lime"},
  {id:"words",name:"Palavras em órbita",desc:"Letras embaralhadas esperando por uma boa ideia.",subject:"Português",icon:BookOpen,color:"pink"},
  {id:"memory",name:"Conexões cósmicas",desc:"Vire as cartas e conecte o que você aprendeu.",subject:"Memória",icon:Brain,color:"purple"},
  {id:"logic",name:"Qual é o próximo?",desc:"Descubra a regra escondida em cada sequência.",subject:"Lógica",icon:Puzzle,color:"orange"},
  {id:"science",name:"Laboratório curioso",desc:"Do nosso corpo ao espaço: investigue o mundo.",subject:"Ciências",icon:FlaskConical,color:"blue"},
  {id:"code",name:"Comando, explorador!",desc:"Monte uma rota e programe sua próxima descoberta.",subject:"Programação",icon:Code2,color:"yellow"},
];
type Save = {age:number; stars:number; completed:Kind[]};
const empty:Save = {age:0,stars:0,completed:[]};
export default function Home(){
 const [save,setSave]=useState<Save>(empty), [ready,setReady]=useState(false), [active,setActive]=useState<Kind|null>(null), [trip,setTrip]=useState(false), [stage,setStage]=useState(0), [seconds,setSeconds]=useState(0), [paused,setPaused]=useState(false), [breakTime,setBreakTime]=useState(false), [finished,setFinished]=useState(false), [round,setRound]=useState(0), [view,setView]=useState("games"), [storageOk,setStorageOk]=useState(true);
 const {resolvedTheme,setTheme}=useTheme();
 const panelRef=useRef<HTMLElement>(null);
 const modalOpen=!!active||breakTime||finished;
 useEffect(()=>{if(!modalOpen)return;const previous=document.activeElement as HTMLElement;const before=document.body.style.overflow;document.body.style.overflow="hidden";
 function keyboard(e:KeyboardEvent){if(e.key==="Escape"){setActive(null);setTrip(false);setBreakTime(false);setFinished(false);setPaused(false);}if(e.key==="Tab"){const buttons=Array.from(panelRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), a[href], input:not([disabled])')||[]).filter(el=>el.offsetParent!==null);const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 document.addEventListener("keydown",keyboard);return()=>{document.body.style.overflow=before;document.removeEventListener("keydown",keyboard);previous?.focus();};},[modalOpen]);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("orbita-v1")||"null");if(v&&Number.isInteger(v.age)&&v.age>=0&&v.age<4&&Number.isFinite(v.stars)&&Array.isArray(v.completed))setSave({age:v.age,stars:Math.max(0,Math.floor(v.stars)),completed:v.completed.filter((id:Kind)=>games.some(g=>g.id===id))});}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem("orbita-v1",JSON.stringify(save));}catch{setStorageOk(false);}},[save,ready]);
 useEffect(()=>{if(!trip||paused||finished)return; const id=setInterval(()=>{if(!document.hidden)setSeconds(s=>s+1);},1000);return()=>clearInterval(id);},[trip,paused,finished]);
 useEffect(()=>{if(!trip)return;if(breakTime&&seconds>=120){setBreakTime(false);setSeconds(0);setActive(games[3].id);}else if(!breakTime&&seconds>=480){setSeconds(0);if(stage===5){setFinished(true);setActive(null);setTrip(false);}else{setStage(stage+1);if(stage===2){setBreakTime(true);setActive(null);}else setActive(games[stage+1].id);}}},[seconds,trip,stage,breakTime]);
 function start(id:Kind){setActive(id);setRound(r=>r+1);setFinished(false);}
 function expedition(){setTrip(true);setStage(0);setSeconds(0);setPaused(false);setBreakTime(false);setFinished(false);start("math");}
 function close(){setActive(null);setTrip(false);setBreakTime(false);setPaused(false);setFinished(false);}
 const selected=games.find(g=>g.id===active);
 const earned=(id:Kind)=>setSave(s=>({...s,stars:s.stars+10,completed:s.completed.includes(id)?s.completed:[...s.completed,id]}));
 return <div className="app-shell">
  <aside className="sidebar" inert={modalOpen}><a href="#" className="brand" aria-label="Órbita, início"><span className="brand-icon"><Sparkles size={24}/></span>órbita<span className="brand-dot">.</span></a><div className="side-label">SEU UNIVERSO</div><nav><button className={view==="games"?"nav-item selected":"nav-item"} onClick={()=>setView("games")}><Map/>Explorar jogos</button><button className={view==="journey"?"nav-item selected":"nav-item"} onClick={()=>setView("journey")}><Rocket/>Minha expedição</button><button className={view==="awards"?"nav-item selected":"nav-item"} onClick={()=>setView("awards")}><Trophy/>Conquistas <span className="count">{save.completed.length}</span></button></nav><div className="side-bottom"><div className="tiny-orbit"><Sparkles/></div><strong>Pequenas descobertas.<br/>Grandes ideias.</strong><p>Cada tentativa é um jeito<br/>novo de aprender.</p><span className="local-note">Sem anúncios. Sem cadastro.</span></div></aside>
  <main inert={modalOpen}><header className="topbar"><span className="breadcrumb">Seu universo <ChevronRight size={15}/><strong>{view==="games"?"Explorar jogos":view==="journey"?"Minha expedição":"Conquistas"}</strong></span><div className="top-actions"><span className="star-wallet"><Star size={18} fill="currentColor"/>{save.stars} <span>estrelas</span></span><button className="icon-button" aria-label="Alternar tema" onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")}>{ready&&resolvedTheme==="dark"?<Sun size={20}/>:<Moon size={20}/>}</button><div className="avatar" aria-label="Explorador"><Rocket size={21}/></div></div></header>
  <div className="content"><div className="page-heading"><div><div className="eyebrow"><span/>CURIOSIDADE ATIVADA</div><h1>{view==="awards"?"Olha o que você descobriu!":view==="journey"?"Uma aventura de cada vez.":"Bora descobrir algo novo?"}</h1><p>Escolha um desafio. Teste uma ideia. Surpreenda seu cérebro.</p></div><span className="edition">CLUBE DOS EXPLORADORES <Sparkles size={16}/></span></div>
  <div className="age-row"><span>Sua fase, seu desafio</span><div className="age-tabs" aria-label="Faixa etária">{ages.map((a,i)=><button key={a} aria-pressed={save.age===i} className={save.age===i?"active":""} onClick={()=>setSave(s=>({...s,age:i}))}>{a}</button>)}</div></div>
  {view!=="awards"&&<section className="expedition"><div className="expedition-copy"><div className="pill"><Sparkles size={14}/> APRENDER É UMA AVENTURA</div><h2>Próxima parada:<br/><span>um universo de ideias.</span></h2><p>6 desafios diferentes. Uma pausa para respirar.<br/>Uma expedição feita para a sua curiosidade.</p><div className="hero-actions"><button className="primary" onClick={expedition}><Play size={18} fill="currentColor"/>Começar expedição</button><span><Clock3 size={16}/>50 min com pausa</span></div></div><div className="mission-map" aria-label="Trilha com seis desafios"><div className="map-caption">MAPA DA EXPEDIÇÃO <span>01 / 06</span></div><div className="map-nodes">{games.map((g,i)=><button key={g.id} className={`map-node node-${i} ${g.color}`} aria-label={`Jogar ${g.name}`} onClick={()=>start(g.id)}><g.icon size={i===0?32:25}/><small>{String(i+1).padStart(2,"0")}</small></button>)}</div><div className="map-footer"><Flag size={16}/> O melhor destino é o que você aprende.</div></div></section>}
  {view==="journey"?<section className="journey-detail"><div className="section-heading"><h2>Seu roteiro de descobertas</h2><span>48 min de jogos + 2 min de pausa</span></div><div className="route-list">{games.map((g,i)=><div key={g.id}><span className={`route-number ${g.color}`}>{i+1}</span><g.icon/><strong>{g.name}</strong><span>8 min</span>{i===2&&<small><Coffee size={16}/> Depois desta missão: água, alongamento e 2 min de pausa.</small>}</div>)}</div><p>O relógio pausa quando você sai da aba. Você pode pausar ou encerrar quando quiser.</p></section>:view==="awards"?<section className="awards-grid">{games.map(g=><article key={g.id} className={`award ${save.completed.includes(g.id)?"earned":""}`}><span className={`game-icon ${g.color}`}><g.icon size={30}/></span><h3>{g.subject}</h3><p>{save.completed.includes(g.id)?"Primeira descoberta conquistada!":"Complete um desafio para conquistar."}</p><button onClick={()=>start(g.id)}>Jogar agora</button></article>)}</section>:<><div className="section-heading"><div><h2>Qual vai ser a descoberta de hoje?</h2><p>Jogue no seu ritmo. Aqui, tentar de novo faz parte.</p></div><span className="game-total">6 jogos · {ages[save.age]}</span></div><section className="game-grid">{games.map((g,i)=><button className="game-card" key={g.id} onClick={()=>start(g.id)}><div className={`card-art ${g.color}`}><span className="subject-label">{g.subject}</span><g.icon className="main-game-icon" size={64} strokeWidth={1.5}/><span className="card-number">0{i+1}</span>{save.completed.includes(g.id)&&<span className="completed-mark"><Check size={15}/></span>}</div><div className="card-copy"><h3>{g.name}</h3><p>{g.desc}</p><div className="card-bottom"><span><Clock3 size={14}/> No seu ritmo</span><span className="play-circle"><Play size={14} fill="currentColor"/></span></div></div></button>)}</section></>}
  <footer><span><Sparkles size={16}/> Aprender vale mais do que acertar de primeira.</span><span>{storageOk?"Progresso salvo só neste aparelho":"Armazenamento indisponível: progresso apenas nesta sessão"}</span></footer></div></main>
  {(active||breakTime||finished)&&<div className="game-overlay"><section ref={panelRef} className="play-panel" role="dialog" aria-modal="true" aria-labelledby="game-title"><header className="play-header"><div><span className="eyebrow">{trip?`EXPEDIÇÃO · MISSÃO ${stage+1} DE 6`:"MODO LIVRE"} · {ages[save.age]}</span><h2 id="game-title">{finished?"Expedição concluída!":breakTime?"Uma pausa também é descoberta.":selected?.name}</h2></div><button autoFocus className="icon-button" onClick={close} aria-label="Sair do jogo"><X/></button></header>{trip&&<div className="session-bar"><span><Clock3 size={16}/>{breakTime?"Pausa":"Tempo nesta missão"} {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")} / {breakTime?"2:00":"8:00"}</span><button onClick={()=>setPaused(p=>!p)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?"Continuar":"Pausar"}</button></div>}{finished?<div className="finish-screen"><Trophy size={64}/><h3>Seu universo ficou maior.</h3><p>Você explorou seis jeitos de aprender. Agora vale descansar e contar a alguém sua descoberta favorita.</p><button className="primary" onClick={close}>Voltar ao universo</button></div>:paused?<div className="finish-screen"><Pause size={50}/><h3>No seu tempo.</h3><button className="primary" onClick={()=>setPaused(false)}>Continuar aventura</button></div>:breakTime?<div className="finish-screen"><Coffee size={60}/><h3>Levanta, estica e bebe uma água.</h3><p>Olhe para longe da tela e encontre três coisas da mesma cor. A próxima missão começa depois da pausa.</p></div>:null}{active&&!finished&&!breakTime&&<div hidden={paused}><Game key={`${active}-${round}`} kind={active} age={save.age} paused={paused} onWin={()=>earned(active)}/></div>}</section></div>}
 </div>;
}

